[package]
name = "fido2_client"
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }
publish = { workspace = true }

[dependencies]
base64 = { workspace = true }
ctap-hid-fido2 = "3.5.1"
pinentry = "0.5.0"
serde = { workspace = true, features = ["derive"] }
secrecy = "0.8.0"
sha2 = { workspace = true }
