[package]
name = "fido2_client"
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }
publish = { workspace = true }

[dependencies]
base64.workspace = true
ctap-hid-fido2 = "3.5.1"
pinentry = "0.5.0"
home = "=0.5.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
secrecy = "0.8.0"
hex = { workspace = true }
webauthn-authenticator-rs = { path = "../../../../../webauthn-rs/webauthn-authenticator-rs/", features = ["win10"] }
tokio.workspace = true
futures-util = "0.3.31"
sha2 = { workspace = true }
webauthn-rs-proto = { path = "../../../../../webauthn-rs/webauthn-rs-proto" }
base64urlsafedata = { path= "../../../../../webauthn-rs/base64urlsafedata" }

